---
# The host ID to use for the installation.
hostId: "04074ddc"

# The flake to use for the installation.
flake: github:MAHDTech/nix-config

# Settings for the UEFI partition.
uefi:
  disk: /dev/disk/by-id/usb-SanDisk_Cruzer_Dial_4C530000171227116262-0:0
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: ZPOOL
    compression: true
    encryption: true
    mirror: false
    stripe: true
  disks:
    - /dev/disk/by-id/nvme-Corsair_MP600_PRO_NH_A5JVB427305AF2
    - /dev/disk/by-id/nvme-Corsair_MP600_PRO_NH_A5JVB4273059HX

# Settings for the swap partition.
swap:
  enabled: true
  size: 4GiB
