---
# Name: Example
# Description: Example starting config.

# Settings for NixOS
nixos:
  # The host ID to use for the installation.
  # Leave blank to generate a random one.
  hostId: ""

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#TEMPLATE

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: false

# Settings for the UEFI partition.
uefi:
  disk: /dev/disk/by-id/some-valid-disk-id-here
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: zpool
    compression: true
    encryption: true
    mirror: false
    stripe: false
  disks:
    - /dev/disk/by-id/another-valid-disk-id-here

# Settings for the swap partition.
swap:
  enabled: false
