---
# Name: HYPERVISOR-2
# Description: Hypervisor Node 2

# Settings for NixOS
nixos:
  # The host ID to use for the installation.
  hostId: "def90002"

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#HYPERVISOR-2

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: false

# Settings for the UEFI partition.
uefi:
  # USB Flash Drive
  disk: /dev/disk/by-id/usb-Samsung_Flash_Drive_0372823110005095-0:0
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: zpool
    compression: true
    size: 0
    type: raidz
    disks:
      # L2ARC
      cache:
        # M.2 SSD
        - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_250GB_S465NB0K439334K
        # M.2 NVMe
        - /dev/disk/by-id/ata-SPCC_M.2_SSD_AA000000000000000283

      # ZIL
      log:
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_20250307C0409
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_20250307C2527
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_20250307C2544
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_AA240816S3102401326

      # Data
      data:
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR50EKPB
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR51VNFJ
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR52K85P
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR52LLRL

      # Hot Spares
      spare: []

# Settings for the swap partition.
swap:
  enabled: false
