---
# Name: HYPERVISOR-3
# Description: Hypervisor Node 3

# Settings for NixOS
nixos:
  # The host ID to use for the installation.
  hostId: "def90003"

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#HYPERVISOR-3

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: false

# Settings for the UEFI partition.
uefi:
  # USB Flash Drive
  disk: /dev/disk/by-id/
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: zpool
    compression: true
    size: 0
    type: raidz
    disks:
      # L2ARC
      cache:
        # M.2 SSD
        - /dev/disk/by-id/
        # M.2 NVMe
        - /dev/disk/by-id/

      # ZIL
      log:
        # SATA SSD
        - /dev/disk/by-id/
        # SATA SSD
        - /dev/disk/by-id/
        # SATA SSD
        - /dev/disk/by-id/
        # SATA SSD
        - /dev/disk/by-id/

      # Data
      data:
        # SATA HDD
        - /dev/disk/by-id/
        # SATA HDD
        - /dev/disk/by-id/
        # SATA HDD
        - /dev/disk/by-id/
        # SATA HDD
        - /dev/disk/by-id/

      # Hot Spares
      spare: []

# Settings for the swap partition.
swap:
  enabled: false

