---
# Name: HYPERVISOR-1
# Description: Hypervisor Node 1

# Settings for NixOS
nixos:
  # The host ID to use for the installation.
  hostId: "def90001"

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#HYPERVISOR-1

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: false

# Settings for the UEFI partition.
uefi:
  # USB Flash Drive
  disk: /dev/disk/by-id/usb-Samsung_Flash_Drive_0373623100000896-0:0
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: zpool
    compression: true
    size: 0
    type: raidz
    disks:
      # L2ARC
      cache:
        # M.2 SSD
        - /dev/disk/by-id/ata-ORICO_9JZ6FOMPEXCNQ51JEYR2
        # M.2 NVMe
        - /dev/disk/by-id/nvme-INTEL_SSDPEKKW010T8_BTHH91230KR51P0E

      # ZIL
      log:
        # SATA SSD
        - /dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S74ZNX0Y344304V
        # SATA SSD
        - /dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S74ZNX0Y344309A
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_AA240816S3102401329
        # SATA SSD
        - /dev/disk/by-id/ata-SPCC_Solid_State_Disk_00000000000000000001

      # Data
      data:
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR519CKW
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR52EWSA
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR548VPC
        # SATA HDD
        - /dev/disk/by-id/ata-ST18000NE000-2YY101_ZR54904J

      # Hot Spares
      spare: []

# Settings for the swap partition.
swap:
  enabled: false

# Settings for Containers/Docker
containers:
  enabled: false

# Settings for Incus.
incus:
  enabled: true
