---

# Name: JONS
# Description: AMD Ryzen Desktop PC with NVIDIA GPU.

# Settings for NixOS
nixos:

  # The host ID to use for the installation.
  hostId: "def10002"

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#JONS

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: true

# Settings for the UEFI partition.
uefi:
  disk: /dev/disk/by-id/usb-Samsung_Flash_Drive_FIT_0360721030005469-0:0
  label: ESP
  size: 4GiB

# Settings for the ZFS pool.
zfs:
  pool:
    name: ZPOOL
    compression: true
    encryption: true
    mirror: false
    stripe: false
  disks:
    - /dev/disk/by-id/nvme-Corsair_MP600_PRO_NH_A5JVB4273059HX

# Settings for the swap partition.
swap:
  enabled: true
  size: 69GiB
