---
# Name: vsphere-template
# Description: A template used for vSphere Virtual Machines.

# Settings for NixOS
nixos:
  # The host ID to use for the installation.
  hostId: "def00000"

  # The flake to use for the installation.
  flake: github:MAHDTech/nix-config#JONS

  # The NixOS configuration partition on the uefi disk.
  config:
    enabled: false

# Settings for the UEFI partition.
uefi:
  disk: /dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:0:0
  label: ESP
  size: 100%

# Settings for the ZFS pool.
zfs:
  pool:
    name: zpool
    compression: true
    encryption: false
    mirror: false
    stripe: false
  disks:
    - /dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:1:0

# Settings for the swap partition.
swap:
  enabled: false
