schema = 3

[mod]
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.10"
    hash = "sha256-ha8NJOAWcmEfQaybfNxyUupt0+zlWxoAKLjCacew43s="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.28.0"
    hash = "sha256-uKGZF1ChxE2aLeiU2V5YtzMqae+ksNI/UwZedOdpRmo="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."golang.org/x/crypto"]
    version = "v0.43.0"
    hash = "sha256-Klv4v0G024WY2OWXsOEl4sKKI+SsUyqx++als1B6yn4="
  [mod."golang.org/x/sys"]
    version = "v0.37.0"
    hash = "sha256-5aT0xP02sW1o9sfJHtWoGGNVYDdwb9FyiX/n6RAlzPo="
  [mod."golang.org/x/text"]
    version = "v0.30.0"
    hash = "sha256-VPT1Y2zzgdk+Q3Gx8hdwKdxbVh0/Zn/HwDpILCW3ZNA="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
