---
##################################################
# Name: Go
# Description: Workflow to build and test on PRs.
##################################################

name: Go

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - src/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  pull-requests: read
  statuses: read

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Go
  GO111MODULE: on # yamllint disable-line rule:truthy
  GOHOME: ${{ github.workspace }}/src

defaults:
  run:
    shell: bash

jobs:
  #########################################################
  # Test
  #########################################################

  test:
    # yamllint disable-line rule:line-length
    name: Go Test (${{ matrix.go-version }}, ${{ matrix.go-os }}-${{ matrix.go-arch }})
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.24"
          - "1.25"
        go-os:
          - "linux"
          - "darwin"
        go-arch:
          - "amd64"
          - "arm64"
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: false
          submodules: recursive

      - id: go_setup
        name: Set up Go (${{ matrix.go-version }})
        uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version: ${{ matrix.go-version }}

      - id: go_check
        name: Go Check (${{ matrix.go-version }})
        run: |
          go version
          go env

      - id: go_mod_download
        name: Get dependencies
        run: |
          cd ${{ env.GOHOME }}
          go mod download

      - id: go_test
        name: Go Test (${{ matrix.go-version }})
        run: |
          cd ${{ env.GOHOME }}
          go test -v ./...

      - id: go_staticcheck
        name: Go Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          working-directory: ${{ env.GOHOME }}
          version: "latest"

      - id: go_vet
        name: Go Vet
        run: |
          cd ${{ env.GOHOME }}
          go vet ./...

      - id: go_lint
        name: Go Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ env.GOHOME }}
          version: latest
          args: >
            --config=${{ github.workspace }}/.linters/config/.golangci.yml
            --timeout=30m
            --issues-exit-code=1

      - id: go_build
        name: Go Build (${{ matrix.go-version }}, ${{ matrix.go-os }}-${{ matrix.go-arch }})
        env:
          GOOS: ${{ matrix.go-os }}
          GOARCH: ${{ matrix.go-arch }}
          ARTIFACT_NAME: ${{ env.PROJECT }}-${{ matrix.go-version }}-${{ matrix.go-os }}-${{ matrix.go-arch }}
        run: |
          cd ${{ env.GOHOME }}
          mkdir -p artifacts
          go build -v -o artifacts/${{ env.ARTIFACT_NAME }}
          echo "✅ Built artifact: ${{ env.ARTIFACT_NAME }}"
